package com.jbpm7.subprocesses;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable {

	static final long serialVersionUID = 1L;
	
    @org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;
	private java.lang.Integer ssn;
	private java.lang.Integer loanAmount;
	private java.lang.Integer loanApproval;
	private java.lang.Integer creditScore;

	public Person() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getSsn() {
		return this.ssn;
	}

	public void setSsn(java.lang.Integer ssn) {
		this.ssn = ssn;
	}

	public java.lang.Integer getLoanAmount() {
		return this.loanAmount;
	}

	public void setLoanAmount(java.lang.Integer loanAmount) {
		this.loanAmount = loanAmount;
	}

	public java.lang.Integer getLoanApproval() {
		return this.loanApproval;
	}

	public void setLoanApproval(java.lang.Integer loanApproval) {
		this.loanApproval = loanApproval;
	}

	public java.lang.Integer getCreditScore() {
		return this.creditScore;
	}

	public void setCreditScore(java.lang.Integer creditScore) {
		this.creditScore = creditScore;
	}

	public Person(java.lang.String name, java.lang.Integer ssn,
			java.lang.Integer loanAmount, java.lang.Integer loanApproval,
			java.lang.Integer creditScore) {
		this.name = name;
		this.ssn = ssn;
		this.loanAmount = loanAmount;
		this.loanApproval = loanApproval;
		this.creditScore = creditScore;
	}

}